### ISSUE TITLE
Getting Error on "ryaxtech/ryax-adm:latest" installation failed on docker side.

### ISSUE THREAD

**Issue by CMRAJ2** [RyaxTech/ryax-engine#3]
Dear Ryax Team,

I am writing to seek your assistance with regards to the installation of your application on my local system using Docker, as per the instructions mentioned in your documentation.

Unfortunately, I am encountering some difficulties while trying to install the "ryaxtech/ryax-adm:latest" Docker container. The Ryax installation is failing repeatedly, and although the localhost webserver seems to be functioning, I am unable to create any workflows. Whenever I click on any part of the webapp, it returns a 404 error. Please help me to install the Ryax application on my local system.
I have attached the log file and screenshot below.

![image](https://user-images.githubusercontent.com/58393081/235626461-9da12cad-94bb-4d82-81bf-99589c4cf2cc.png)
[ryax-adm-logs.txt](https://github.com/RyaxTech/ryax/files/11371526/ryax-adm-logs.txt)

Best regards,
Chandra Mohan

**Comment by mickours** [comment]
The installation process as been fixed, closing. Please feel free to add a comment if you still have some issue
